## Q1

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods 

(c) Compare the following numpy arrays: 

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]]) 

(d) Find the most frequent value and their indice(s) in the following arrays: 

i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 

i. Sum of all elements 

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise 
 
(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 

i. Sum of diagonal elements 

ii. Eigen values of matrix

iii. Eigen vectors of matrix 

iv. Inverse of matrix 

v. Determinant of matrix  
 
(g) Multiply the following matrices and also find covariance between matrices using NumPy: 

i. p = [[1, 2], [2, 3]] 

   q = [[4, 5], [6, 7]] 

ii. p = [[1, 2], [2, 3], [4, 5]] 

    q = [[4, 5, 1], [6, 7, 2]] 

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product? 

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
reversed_arr=np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


In [2]:
arr=np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened=arr.flatten()
print(flattened)

[1 2 3 2 4 5 1 2 3]


In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
result=np.equal(x,y)
print(result)


[[ True  True]
 [ True  True]]


In [4]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
ans=np.bincount(x)
print(ans)
freq=np.argmax(ans)
print(freq)
print(np.where(x==freq))

[0 5 2 1 1 1]
1
(array([0, 5, 7, 8, 9]),)


In [5]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
ans=np.bincount(x)
print(ans)
freq=np.argmax(ans)
print(np.where(x==freq))

[0 5 2 1 1 1]
(array([0, 5, 7, 8, 9]),)


In [6]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(gfg))
print("Sum of Rows are:")
print(np.sum(gfg,axis=1))
print("Sum of Columns are:")
print(np.sum(gfg,axis=0))

45
Sum of Rows are:
[[14]
 [16]
 [15]]
Sum of Columns are:
[[20  9 16]]


In [7]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.trace(n_array))
eigenvalues,eigenvectors=np.linalg.eig(n_array)
print("Eigen Values are:",eigenvalues)
print("Eigen Vectors are:",eigenvectors)
print("Inverse of the matrix is:")
print(np.linalg.inv(n_array))
print("Determinant of the matrix is:",np.linalg.det(n_array))

176
Eigen Values are: [98.16835147 28.097044   49.73460452]
Eigen Vectors are: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix is:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix is: 137180.0000000001


In [16]:
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
multiplied=np.dot(p,q)
print(multiplied)
print("Covariance between matrices are:",np.cov(p,q))

[[16 19]
 [26 31]]
Covariance between matrices are: [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [15]:
p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])
multiplied=np.inner(q,p)
print(multiplied)
print("Covariance between matrices are:",np.cov(p,q))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
from itertools import product
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("Cartesian Product is:")
print(np.array(list(product(x.flatten(),y.flatten()))))
print("Inner product is:",np.inner(x,y))
print("Outer product is:",np.outer(x,y))

Cartesian Product is:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]
Inner product is: [[17 52]
 [13 62]]
Outer product is: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


## Q2:-


(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value 

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and 
each row 

(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values 


 




In [24]:
array=np.array([[1,-2,3],[-4,5,-6]])
print(np.abs(array))
flattened=array.flatten()
print("25,50,75 Percentile of flattened array:")
print(np.percentile(flattened,25))
print(np.percentile(flattened,50))
print(np.percentile(flattened,75))
print("25,50,75 Percentile of each column:")
print(np.percentile(array,25,axis=0))
print(np.percentile(array,50,axis=0))
print(np.percentile(array,75,axis=0))
print("25,50,75 Percentile of each row:")
print(np.percentile(array,25,axis=1))
print(np.percentile(array,50,axis=1))
print(np.percentile(array,75,axis=1))

[[1 2 3]
 [4 5 6]]
25,50,75 Percentile of flattened array:
-3.5
-0.5
2.5
25,50,75 Percentile of each column:
[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]
25,50,75 Percentile of each row:
[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]


In [25]:
print("Mean,Median,Standard Deviation of flattened Array")
print(np.mean(flattened))
print(np.median(flattened))
print(np.std(flattened))
print("Mean,Median,Standard Deviation of each column")
print(np.mean(array,axis=0))
print(np.median(array,axis=0))
print(np.std(array,axis=0))
print("Mean,Median,Standard Deviation of each row")
print(np.mean(array,axis=1))
print(np.median(array,axis=1))
print(np.std(array,axis=1))

Mean,Median,Standard Deviation of flattened Array
-0.5
-0.5
3.8622100754188224
Mean,Median,Standard Deviation of each column
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
Mean,Median,Standard Deviation of each row
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [26]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))
print(np.round(a))

[-1. -1. -0.  1.  2.  2.  3.]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


## Q3

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i. Sorted array 

ii. Indices of sorted array 

iii. 4 smallest elements

iv. 5 largest elements

(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 

i. Integer elements only 

ii. Float elements only



In [27]:
array= np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array=np.sort(array)
print(sorted_array)
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [28]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array[np.floor(array)==array])
print(array[np.floor(array)!=array])

[1. 2. 3. 2.]
[1.2 2.2]


## Q4

(a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images) 

(b) Load the saved file into jupyter notebook?

In [23]:
from PIL import Image
import numpy as np
import os

def img_to_array(image_path):
    image = Image.open(image_path)
    image_array = np.array(image)
    if len(image_array.shape) == 2:
        np.savetxt("grayscale_image.txt", image_array, fmt='%d')
        print("Grayscale image saved as 'grayscale_image.txt'")
    else:
        height, width, channels = image_array.shape
        flattened = image_array.reshape(-1, channels)
        np.savetxt("rgb_image.txt", flattened, fmt='%d')
        with open("rgb_shape.txt", "w") as shape_file:
            shape_file.write(f"{height} {width}")
        print("RGB image saved as 'rgb_image.txt' and shape saved in 'rgb_shape.txt'")

def load_saved_image():
    if os.path.exists("grayscale_image.txt"):
        grayscale = np.loadtxt("grayscale_image.txt", dtype=int)
        print("📥 Loaded Grayscale Image Array:")
        print(grayscale)
        return grayscale
    elif os.path.exists("rgb_image.txt") and os.path.exists("rgb_shape.txt"):
        with open("rgb_shape.txt", "r") as shape_file:
            height, width = map(int, shape_file.read().split())
        rgb_data = np.loadtxt("rgb_image.txt", dtype=int).reshape(height, width, 3)
        print("Loaded RGB Image Array:")
        print(rgb_data)
        return rgb_data
    else:
        print("No saved image file found.")
        return None

img_to_array(r"C:\Users\kavis\OneDrive\Pictures\download.jpeg")
loaded_image = load_saved_image()


RGB image saved as 'rgb_image.txt' and shape saved in 'rgb_shape.txt'
Loaded RGB Image Array:
[[[107 145 207]
  [107 145 207]
  [107 145 207]
  ...
  [ 63 131 206]
  [ 63 131 206]
  [ 62 130 205]]

 [[110 148 210]
  [110 148 210]
  [110 148 210]
  ...
  [ 64 132 207]
  [ 64 132 207]
  [ 64 132 207]]

 [[113 151 213]
  [113 151 213]
  [113 151 213]
  ...
  [ 67 135 208]
  [ 66 134 207]
  [ 66 134 207]]

 ...

 [[112 161 217]
  [113 162 218]
  [113 162 218]
  ...
  [ 42 136 200]
  [ 42 136 200]
  [ 42 136 200]]

 [[108 157 213]
  [108 157 213]
  [108 157 213]
  ...
  [ 36 131 195]
  [ 36 131 195]
  [ 36 131 195]]

 [[106 155 211]
  [106 155 211]
  [106 155 211]
  ...
  [ 31 129 194]
  [ 31 129 194]
  [ 31 129 194]]]
